# Generated by Django 4.0.2 on 2022-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userId',
            new_name='productID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nbrFollowers',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
    ]
