# Generated by Django 4.0.2 on 2022-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.IntegerField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
